// Code generated by ent, DO NOT EDIT.

package ogent

import "github.com/akifkadioglu/entgo-demo-2/ent"

func NewTableExample(e *ent.TableExample) *TableExample {
	if e == nil {
		return nil
	}
	var ret TableExample
	ret.ID = e.ID
	ret.Field1 = e.Field1
	ret.Field2 = e.Field2
	return &ret
}

func NewTableExamples(es []*ent.TableExample) []TableExample {
	if len(es) == 0 {
		return nil
	}
	r := make([]TableExample, len(es))
	for i, e := range es {
		r[i] = NewTableExample(e).Elem()
	}
	return r
}

func (te *TableExample) Elem() TableExample {
	if te == nil {
		return TableExample{}
	}
	return *te
}
