// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/akifkadioglu/entgo-demo-2/ent/schema"
	"github.com/akifkadioglu/entgo-demo-2/ent/tableexample"
)

// TableExample is the model entity for the TableExample schema.
type TableExample struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Field1 holds the value of the "field1" field.
	Field1 []schema.FieldStruct `json:"field1,omitempty"`
	// Field2 holds the value of the "field2" field.
	Field2       schema.FieldStruct `json:"field2,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TableExample) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case tableexample.FieldField1, tableexample.FieldField2:
			values[i] = new([]byte)
		case tableexample.FieldID:
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TableExample fields.
func (te *TableExample) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case tableexample.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			te.ID = int(value.Int64)
		case tableexample.FieldField1:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field field1", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &te.Field1); err != nil {
					return fmt.Errorf("unmarshal field field1: %w", err)
				}
			}
		case tableexample.FieldField2:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field field2", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &te.Field2); err != nil {
					return fmt.Errorf("unmarshal field field2: %w", err)
				}
			}
		default:
			te.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TableExample.
// This includes values selected through modifiers, order, etc.
func (te *TableExample) Value(name string) (ent.Value, error) {
	return te.selectValues.Get(name)
}

// Update returns a builder for updating this TableExample.
// Note that you need to call TableExample.Unwrap() before calling this method if this TableExample
// was returned from a transaction, and the transaction was committed or rolled back.
func (te *TableExample) Update() *TableExampleUpdateOne {
	return NewTableExampleClient(te.config).UpdateOne(te)
}

// Unwrap unwraps the TableExample entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (te *TableExample) Unwrap() *TableExample {
	_tx, ok := te.config.driver.(*txDriver)
	if !ok {
		panic("ent: TableExample is not a transactional entity")
	}
	te.config.driver = _tx.drv
	return te
}

// String implements the fmt.Stringer.
func (te *TableExample) String() string {
	var builder strings.Builder
	builder.WriteString("TableExample(")
	builder.WriteString(fmt.Sprintf("id=%v, ", te.ID))
	builder.WriteString("field1=")
	builder.WriteString(fmt.Sprintf("%v", te.Field1))
	builder.WriteString(", ")
	builder.WriteString("field2=")
	builder.WriteString(fmt.Sprintf("%v", te.Field2))
	builder.WriteByte(')')
	return builder.String()
}

// TableExamples is a parsable slice of TableExample.
type TableExamples []*TableExample
