// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/akifkadioglu/entgo-demo-2/ent/predicate"
	"github.com/akifkadioglu/entgo-demo-2/ent/tableexample"
)

// TableExampleDelete is the builder for deleting a TableExample entity.
type TableExampleDelete struct {
	config
	hooks    []Hook
	mutation *TableExampleMutation
}

// Where appends a list predicates to the TableExampleDelete builder.
func (ted *TableExampleDelete) Where(ps ...predicate.TableExample) *TableExampleDelete {
	ted.mutation.Where(ps...)
	return ted
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ted *TableExampleDelete) Exec(ctx context.Context) (int, error) {
	return withHooks[int, TableExampleMutation](ctx, ted.sqlExec, ted.mutation, ted.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (ted *TableExampleDelete) ExecX(ctx context.Context) int {
	n, err := ted.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ted *TableExampleDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(tableexample.Table, sqlgraph.NewFieldSpec(tableexample.FieldID, field.TypeInt))
	if ps := ted.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ted.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	ted.mutation.done = true
	return affected, err
}

// TableExampleDeleteOne is the builder for deleting a single TableExample entity.
type TableExampleDeleteOne struct {
	ted *TableExampleDelete
}

// Where appends a list predicates to the TableExampleDelete builder.
func (tedo *TableExampleDeleteOne) Where(ps ...predicate.TableExample) *TableExampleDeleteOne {
	tedo.ted.mutation.Where(ps...)
	return tedo
}

// Exec executes the deletion query.
func (tedo *TableExampleDeleteOne) Exec(ctx context.Context) error {
	n, err := tedo.ted.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{tableexample.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (tedo *TableExampleDeleteOne) ExecX(ctx context.Context) {
	if err := tedo.Exec(ctx); err != nil {
		panic(err)
	}
}
