// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/akifkadioglu/entgo-demo-2/ent/schema"
	"github.com/akifkadioglu/entgo-demo-2/ent/tableexample"
)

// TableExampleCreate is the builder for creating a TableExample entity.
type TableExampleCreate struct {
	config
	mutation *TableExampleMutation
	hooks    []Hook
}

// SetField1 sets the "field1" field.
func (tec *TableExampleCreate) SetField1(ss schema.FieldStruct) *TableExampleCreate {
	tec.mutation.SetField1(ss)
	return tec
}

// SetField2 sets the "field2" field.
func (tec *TableExampleCreate) SetField2(ss []schema.FieldStruct) *TableExampleCreate {
	tec.mutation.SetField2(ss)
	return tec
}

// Mutation returns the TableExampleMutation object of the builder.
func (tec *TableExampleCreate) Mutation() *TableExampleMutation {
	return tec.mutation
}

// Save creates the TableExample in the database.
func (tec *TableExampleCreate) Save(ctx context.Context) (*TableExample, error) {
	return withHooks[*TableExample, TableExampleMutation](ctx, tec.sqlSave, tec.mutation, tec.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (tec *TableExampleCreate) SaveX(ctx context.Context) *TableExample {
	v, err := tec.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tec *TableExampleCreate) Exec(ctx context.Context) error {
	_, err := tec.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tec *TableExampleCreate) ExecX(ctx context.Context) {
	if err := tec.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tec *TableExampleCreate) check() error {
	if _, ok := tec.mutation.Field1(); !ok {
		return &ValidationError{Name: "field1", err: errors.New(`ent: missing required field "TableExample.field1"`)}
	}
	if _, ok := tec.mutation.Field2(); !ok {
		return &ValidationError{Name: "field2", err: errors.New(`ent: missing required field "TableExample.field2"`)}
	}
	return nil
}

func (tec *TableExampleCreate) sqlSave(ctx context.Context) (*TableExample, error) {
	if err := tec.check(); err != nil {
		return nil, err
	}
	_node, _spec := tec.createSpec()
	if err := sqlgraph.CreateNode(ctx, tec.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	tec.mutation.id = &_node.ID
	tec.mutation.done = true
	return _node, nil
}

func (tec *TableExampleCreate) createSpec() (*TableExample, *sqlgraph.CreateSpec) {
	var (
		_node = &TableExample{config: tec.config}
		_spec = sqlgraph.NewCreateSpec(tableexample.Table, sqlgraph.NewFieldSpec(tableexample.FieldID, field.TypeInt))
	)
	if value, ok := tec.mutation.Field1(); ok {
		_spec.SetField(tableexample.FieldField1, field.TypeJSON, value)
		_node.Field1 = value
	}
	if value, ok := tec.mutation.Field2(); ok {
		_spec.SetField(tableexample.FieldField2, field.TypeJSON, value)
		_node.Field2 = value
	}
	return _node, _spec
}

// TableExampleCreateBulk is the builder for creating many TableExample entities in bulk.
type TableExampleCreateBulk struct {
	config
	builders []*TableExampleCreate
}

// Save creates the TableExample entities in the database.
func (tecb *TableExampleCreateBulk) Save(ctx context.Context) ([]*TableExample, error) {
	specs := make([]*sqlgraph.CreateSpec, len(tecb.builders))
	nodes := make([]*TableExample, len(tecb.builders))
	mutators := make([]Mutator, len(tecb.builders))
	for i := range tecb.builders {
		func(i int, root context.Context) {
			builder := tecb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TableExampleMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, tecb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, tecb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, tecb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (tecb *TableExampleCreateBulk) SaveX(ctx context.Context) []*TableExample {
	v, err := tecb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tecb *TableExampleCreateBulk) Exec(ctx context.Context) error {
	_, err := tecb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tecb *TableExampleCreateBulk) ExecX(ctx context.Context) {
	if err := tecb.Exec(ctx); err != nil {
		panic(err)
	}
}
