// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// TableExample is the predicate function for tableexample builders.
type TableExample func(*sql.Selector)
